import type { MarketplaceOffer } from "./marketplace-types";

export const fallbackMarketplaceOffers: MarketplaceOffer[] = [
  {
    id: "HP-1048",
    business: "BrightCare Clinic",
    debtor: "Maya Lopez",
    category: "Service receivable",
    summary: "Dental treatment plan acknowledged by the patient.",
    amount: "$12,800",
    fundingPrice: "$12,120",
    expectedRepayment: "$12,800",
    due: "Aug 18, 2026",
    term: "43 days",
    risk: "Low",
    repaymentAsset: "USDC",
    status: "Listed",
    verification: "KYB verified",
    acknowledgement: "Debtor acknowledged",
    industry: "Clinic services",
    dueInDays: "43 days",
    fundedShare: "94.7%",
    onchainOfferId: "1048",
    metadataHash: "hp_meta_1048_brightcare",
    notes: [
      "Treatment plan was accepted before marketplace listing.",
      "Repayment follows the debtor acknowledgment milestone.",
    ],
    proof: [
      "Signed service estimate",
      "KYB record from business onboarding",
      "Debtor acknowledgment timestamp",
    ],
    timeline: [
      { label: "Created", value: "Jun 19, 2026" },
      { label: "Acknowledged", value: "Jun 20, 2026" },
      { label: "Listed", value: "Jun 21, 2026" },
      { label: "Expected repayment", value: "Aug 18, 2026" },
    ],
  },
  {
    id: "HP-1052",
    business: "Northline Supply",
    debtor: "Tidepoint Retail",
    category: "Invoice",
    summary: "Wholesale equipment invoice with 45-day repayment terms.",
    amount: "$24,000",
    fundingPrice: "$22,980",
    expectedRepayment: "$24,000",
    due: "Sep 02, 2026",
    term: "58 days",
    risk: "Moderate",
    repaymentAsset: "USDC",
    status: "Listed",
    verification: "KYB verified",
    acknowledgement: "Debtor acknowledged",
    industry: "B2B supply",
    dueInDays: "58 days",
    fundedShare: "95.8%",
    onchainOfferId: "1052",
    metadataHash: "hp_meta_1052_northline",
    notes: [
      "Invoice amount covers a single equipment delivery batch.",
      "Settlement aligns with the buyer's standard net terms.",
    ],
    proof: [
      "Issued invoice",
      "Buyer receipt confirmation",
      "Acknowledgment record",
    ],
    timeline: [
      { label: "Created", value: "Jul 05, 2026" },
      { label: "Acknowledged", value: "Jul 06, 2026" },
      { label: "Listed", value: "Jul 08, 2026" },
      { label: "Expected repayment", value: "Sep 02, 2026" },
    ],
  },
  {
    id: "HP-1061",
    business: "Atlas Learning Studio",
    debtor: "Jordan Kim",
    category: "Installment receivable",
    summary: "Course installment receivable acknowledged by the student.",
    amount: "$4,600",
    fundingPrice: "$4,390",
    expectedRepayment: "$4,600",
    due: "Jul 29, 2026",
    term: "23 days",
    risk: "Low",
    repaymentAsset: "USDC",
    status: "Listed",
    verification: "KYB verified",
    acknowledgement: "Debtor acknowledged",
    industry: "Education",
    dueInDays: "23 days",
    fundedShare: "95.4%",
    onchainOfferId: "1061",
    metadataHash: "hp_meta_1061_atlas",
    notes: [
      "Installment plan is linked to the learner enrollment record.",
      "Repayment is expected from the agreed schedule, not open-ended billing.",
    ],
    proof: [
      "Enrollment agreement",
      "Installment schedule",
      "Debtor acknowledgment record",
    ],
    timeline: [
      { label: "Created", value: "Jul 01, 2026" },
      { label: "Acknowledged", value: "Jul 02, 2026" },
      { label: "Listed", value: "Jul 03, 2026" },
      { label: "Expected repayment", value: "Jul 29, 2026" },
    ],
  },
];
