import { getHorizonPayContracts } from "@/lib/contracts/horizonpay-contracts";
import type { WorkspaceData } from "./workspace-types";

const contracts = getHorizonPayContracts();

export const fallbackWorkspaceData: WorkspaceData = {
  contracts,
  source: "fallback",
  roles: [
    {
      role: "business",
      title: "Business workspace",
      summary: "Create backed Offers, request acknowledgement, list receivables, and track liquidity.",
      verification: "KYB verified",
      metrics: [
        { label: "Receivables", value: "$41.4k", detail: "Across 3 active Offers" },
        { label: "Liquidity unlocked", value: "$39.5k", detail: "Funding requests ready" },
        { label: "Pending ACK", value: "1", detail: "Debtor review required" },
      ],
      offers: [
        {
          id: "HP-1048",
          title: "BrightCare Clinic",
          counterparty: "Maya Lopez",
          category: "Service receivable",
          amount: "$12,800",
          fundingPrice: "$12,120",
          due: "Aug 18, 2026",
          status: "Listed",
          risk: "Low",
          metadataHash: "hp_meta_1048_brightcare",
          onchainOfferId: "1048",
        },
        {
          id: "HP-DRAFT",
          title: "New receivable draft",
          counterparty: "Invite debtor",
          category: "Invoice",
          amount: "$8,000",
          fundingPrice: "$7,680",
          due: "Sep 14, 2026",
          status: "Draft",
          risk: "Moderate",
          metadataHash: "pending_hash_generation",
        },
      ],
      operations: [
        {
          id: "fallback-create-offer",
          operation: "Create Offer",
          contractId: contracts.offerRegistry,
          method: "create_offer",
          args: {
            principal_amount: "1280000",
            funding_price: "1212000",
            repayment_asset: "USDC",
          },
          status: "Ready",
        },
        {
          id: "fallback-list-offer",
          operation: "List Offer",
          contractId: contracts.marketplace,
          method: "list_offer",
          args: { offer_id: "1048" },
          status: "Ready",
        },
      ],
      primaryActions: ["Create Offer", "List Offer", "Cancel Offer"],
    },
    {
      role: "debtor",
      title: "Debtor obligations",
      summary: "Review assigned Offers, acknowledge valid obligations, dispute incorrect details, and repay.",
      verification: "Invite verified",
      metrics: [
        { label: "Active obligations", value: "2", detail: "One due within 30 days" },
        { label: "Remaining", value: "$17.4k", detail: "Across acknowledged Offers" },
        { label: "History", value: "4", detail: "Recorded repayment events" },
      ],
      offers: [
        {
          id: "HP-1048",
          title: "Dental treatment plan",
          counterparty: "BrightCare Clinic",
          category: "Service receivable",
          amount: "$12,800",
          fundingPrice: "$12,120",
          due: "Aug 18, 2026",
          status: "Acknowledged",
          risk: "Low",
          metadataHash: "hp_meta_1048_brightcare",
          onchainOfferId: "1048",
        },
      ],
      operations: [
        {
          id: "fallback-acknowledge",
          operation: "Acknowledge Offer",
          contractId: contracts.offerRegistry,
          method: "acknowledge_offer",
          args: { offer_id: "1048" },
          status: "Ready",
        },
        {
          id: "fallback-repay",
          operation: "Repay Full",
          contractId: contracts.settlement,
          method: "repay_full",
          args: { offer_id: "1048", amount: "1280000" },
          status: "Ready",
        },
        {
          id: "fallback-partial-repay",
          operation: "Repay",
          contractId: contracts.settlement,
          method: "repay_offer",
          args: { offer_id: "1048", payer: "wallet_required", amount: "50000" },
          status: "Ready",
        },
        {
          id: "fallback-dispute",
          operation: "Open Dispute",
          contractId: "offchain-review",
          method: "open_dispute",
          args: { offer_id: "1048", reason: "terms_review" },
          status: "Confirmed",
        },
      ],
      primaryActions: ["Acknowledge", "Open Dispute", "Repay", "Repay Full"],
    },
    {
      role: "investor",
      title: "Investor portfolio",
      summary: "Review listed Offers, accept disclosures, fund allocations, and track repayment performance.",
      verification: "Investor approved",
      metrics: [
        { label: "Committed", value: "$39.5k", detail: "3 funded positions" },
        { label: "Expected repayment", value: "$41.4k", detail: "Weighted due window 38d" },
        { label: "Overdue exposure", value: "$0", detail: "No overdue positions" },
      ],
      offers: [
        {
          id: "HP-1052",
          title: "Northline Supply",
          counterparty: "Tidepoint Retail",
          category: "Invoice",
          amount: "$24,000",
          fundingPrice: "$22,980",
          due: "Sep 02, 2026",
          status: "Listed",
          risk: "Moderate",
          metadataHash: "hp_meta_1052_northline",
          onchainOfferId: "1052",
        },
      ],
      operations: [
        {
          id: "fallback-fund",
          operation: "Fund Offer",
          contractId: contracts.marketplace,
          method: "fund_offer",
          args: { offer_id: "1052", investor: "wallet_required" },
          status: "Ready",
        },
      ],
      primaryActions: ["Fund Offer"],
    },
    {
      role: "admin",
      title: "Compliance console",
      summary: "Review verification, flagged metadata, disputes, freezes, and indexed contract events.",
      verification: "Operator",
      metrics: [
        { label: "Open reviews", value: "2", detail: "One high severity" },
        { label: "Frozen Offers", value: "0", detail: "No active freezes" },
        { label: "Indexed events", value: "18", detail: "Across 6 contracts" },
      ],
      offers: [],
      operations: [
        {
          id: "fallback-freeze",
          operation: "Freeze Offer",
          contractId: contracts.offerRegistry,
          method: "freeze_offer",
          args: { offer_id: "1052", reason: "metadata_review" },
          status: "Ready",
        },
      ],
      primaryActions: ["Verify Business", "Verify Debtor", "Verify Investor", "Enable Asset", "Freeze Offer"],
    },
  ],
  adminReviews: [
    {
      id: "review-1",
      subject: "Repeated supplier metadata pattern",
      reason: "Multiple high-value Offers share similar document hashes.",
      status: "Open",
      severity: "High",
      offerId: "HP-1052",
    },
    {
      id: "review-2",
      subject: "Debtor dispute window",
      reason: "Debtor has not confirmed the latest invoice schedule.",
      status: "Open",
      severity: "Medium",
      offerId: "HP-DRAFT",
    },
  ],
};
